#!/bin/sh
git diff --cached --name-only|while read changed_file
do
    ext=${changed_file##*.}
    if [ "$ext" != "php" ]
    then
        continue
    fi

    php -l $changed_file
    ret_code=$?

    if [ $ret_code -ne 0 ]
    then
        exit 1
    fi
done
